/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'
import { Route as PlacementTrackSlugRouteImport } from './routes/placement.$trackSlug'
import { Route as TracksIndexRouteImport } from './routes/tracks.index'
import { Route as TracksSlugRouteImport } from './routes/tracks.$slug'
import { Route as WorkspaceDrillIdRouteImport } from './routes/workspace.$drillId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementTrackSlugRoute = PlacementTrackSlugRouteImport.update({
  id: '/placement/$trackSlug',
  path: '/placement/$trackSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksIndexRoute = TracksIndexRouteImport.update({
  id: '/tracks/',
  path: '/tracks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksSlugRoute = TracksSlugRouteImport.update({
  id: '/tracks/$slug',
  path: '/tracks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceDrillIdRoute = WorkspaceDrillIdRouteImport.update({
  id: '/workspace/$drillId',
  path: '/workspace/$drillId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/placement/$trackSlug': typeof PlacementTrackSlugRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/workspace/$drillId': typeof WorkspaceDrillIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/placement/$trackSlug': typeof PlacementTrackSlugRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/workspace/$drillId': typeof WorkspaceDrillIdRoute
  '/courses': typeof CoursesIndexRoute
  '/tracks': typeof TracksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/placement/$trackSlug': typeof PlacementTrackSlugRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/workspace/$drillId': typeof WorkspaceDrillIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/courses/$slug'
    | '/lessons/$lessonId'
    | '/placement/$trackSlug'
    | '/tracks/$slug'
    | '/workspace/$drillId'
    | '/courses/'
    | '/tracks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/courses/$slug'
    | '/lessons/$lessonId'
    | '/placement/$trackSlug'
    | '/tracks/$slug'
    | '/workspace/$drillId'
    | '/courses'
    | '/tracks'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/courses/$slug'
    | '/lessons/$lessonId'
    | '/placement/$trackSlug'
    | '/tracks/$slug'
    | '/workspace/$drillId'
    | '/courses/'
    | '/tracks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  PlacementTrackSlugRoute: typeof PlacementTrackSlugRoute
  TracksSlugRoute: typeof TracksSlugRoute
  WorkspaceDrillIdRoute: typeof WorkspaceDrillIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  TracksIndexRoute: typeof TracksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement/$trackSlug': {
      id: '/placement/$trackSlug'
      path: '/placement/$trackSlug'
      fullPath: '/placement/$trackSlug'
      preLoaderRoute: typeof PlacementTrackSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/': {
      id: '/tracks/'
      path: '/tracks'
      fullPath: '/tracks/'
      preLoaderRoute: typeof TracksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/$slug': {
      id: '/tracks/$slug'
      path: '/tracks/$slug'
      fullPath: '/tracks/$slug'
      preLoaderRoute: typeof TracksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$drillId': {
      id: '/workspace/$drillId'
      path: '/workspace/$drillId'
      fullPath: '/workspace/$drillId'
      preLoaderRoute: typeof WorkspaceDrillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  PlacementTrackSlugRoute: PlacementTrackSlugRoute,
  TracksSlugRoute: TracksSlugRoute,
  WorkspaceDrillIdRoute: WorkspaceDrillIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  TracksIndexRoute: TracksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
